### ISSUE TITLE
missing diary_generator_builder.py

### ISSUE THREAD

**Issue by josemarfdc** [jonpappalord/DITRAS#3]
The documentation mentions we can use a diary_generator_builder.py to create our own diary generator, however such a file is not included.

Would it be possible for you to git push that file to the repo, please 🙏?
Thank you so much

**Comment by jonpappalord** [comment]
Hi @josemarfdc 
you can find the diary generator builder (as well as a new version of DITRAS) in library scikit-mobility: https://github.com/scikit-mobility/scikit-mobility
Luca
