### ISSUE TITLE
Interactions between Agents.

### ISSUE THREAD

**Issue by fatcatZF** [jonpappalord/DITRAS#6]
Thanks a lot for your work. Can this library simulate the interactions between multiple agents?

**Comment by jonpappalord** [comment]
Hi @fatcatZF. DITRAS cannot, but in library [scikit-mobility](https://github.com/scikit-mobility/scikit-mobility) you can find other models, such as [STS-EPR](https://www.mdpi.com/2220-9964/10/9/599), which take into account the social relationships between agents when performing the mobility simulation. Also, please note that future updates of DITRAS will be on  library [scikit-mobility](https://github.com/scikit-mobility/scikit-mobility) only.
